{extends file='../../site_base.tpl'}

{block name="content"}

    <h3><a href="/health-tips">Health Tips</a></h3>
    
    <!--BREADCRUMBING HERE-->
    <h3 class="sh3"><a href="/health-tips/{$data.location}">{$data.label}</a> / <a href="/health-tips/{$data.location}/managing-diabetes">Managing Diabetes</a> / 
    Healthy Coping</a> </h3>

    <br>

    <!--HTML CONTENT GOES HERE-->
    <h1>7. Healthy Coping </h1>
    <p>Diabetes does not only affect your physical health. Diabetes can also affect your mental and emotional health. This is not uncommon. Building a partnership with your doctor and medical home team can help you process the mental health side of diabetes, too.</p>
    <h3>What Might I Feel…and Why?</h3>
    <p>Some of the feelings you may experience are the result of being diagnosed with diabetes. You may be distressed about your health. You may not feel much control, especially if you have been recently diagnosed. You may be angry, scared, and sad. Diabetes medications may also affect your mood. You may feel tired or down.</p>
    <h3>What Should I Do?</h3>

    <ul>
        <li>At every visit, let your doctor and medical home team know how you are feeling — physically and mentally. This is very important.</li>
        <li>Encourage your friends and family to also help you track your mood.</li>
        <li>Discuss options with your doctor and medical home team that can help you feel better. These may include exercising more, changing a medication, seeing a counselor, and/or changing what you eat.</li>
    </ul>

    <h3>8 Tips for Managing the Emotional Distress that Comes with Having a Chronic Disease</h3>

    <p>Many people experience considerable emotional distress about having a chronic disease and about the complex management that many chronic diseases require. Chronic diseases include diabetes, asthma, heart disease, high blood pressure and high cholesterol, along with many others. Emotional distress often includes frustration with the ongoing burdens of diet, physical activity, disease monitoring, and medication taking - and going to all of the doctors appointments that are required (it can feel like a full time job!!). Other equally important stresses center around fears about the future, concerns about other problems that can result from your chronic disease, limits that the disease causes in the things you can do, difficulties dealing with friends and family members, and keeping up with all of the new medications, treatment suggestions and related recommendations offered by doctors and others. It is no wonder that persons with a chronic disease often report high levels of emotional distress, fatigue, frustration, anger, burnout, poor mood, and even depression. Having a chronic health condition can be overwhelming because of the unending demands for management that the disease requires, and the fears that things might get worse.</p>

    <p>The emotional distress associated with a chronic disease can also have a direct effect on the disease itself. For example, several studies have shown that persons with a chronic disease with high levels of emotional distress manage their diet, physical activity, medication usage, and disease monitoring more poorly, report more family conflict around disease management, display faster onset of additional health problems, have more contact with the health care system, and have higher levels of disease-related problems over time than persons with a chronic health condition who do not have high levels of emotional distress. One reason for this may be physical changes in our bodies caused by the distress. Another key reason is that emotional distress interferes with how well we manage our disease. It is very hard to complete the complicated tasks required by a chronic disease when feelings of tension, distress, sadness, and frustration occur.</p>

    <p>Acknowledging the impact of these kinds of stresses on chronic disease management and on a person’s general feeling of well-being is very important. What can be done in response to feeling distressed, burned out, overwhelmed, and blue? The good news is that there are helpful things you can do to address this kind of disease-related emotional distress. Emotional distress can be managed and reduced if a few important tips are kept in mind.  Not each will work for everyone, because persons with chronic disease have different personal styles, life contexts and preferences. But the ideas underlying these tips apply to most persons with a chronic condition.</p>

    <h4>Tip #1: Feelings of being distressed, overwhelmed and burned out are to be expected.</h4>
    <p>You are not alone! Almost all persons with a chronic disease feel frustrated and distressed from time to time, and some more than others. Chronic disease can be burdensome, and it is normal to react to this burden over time. For example, many people feel frightened after learning about changes in their condition, and they may fear going back to the doctor because of concerns about receiving more bad news. They may blame themselves, other family members, or their healthcare providers, or they may simply feel that they should give up — “what’s the use anyway?” Others feel burned out because of the unending demands of disease management. Having these feelings for more than a week or two, however, often is a sign or signal that these feelings need to be attended to. Monitoring your emotional health and distress is as important as monitoring one’s blood glucose level or blood pressure. Ignoring this part of your chronic disease often makes matters worse; attending to the intensity and type of feeling experienced often provides a clue for what to do next.</p>

    <h4>Tip #2: Consult your healthcare provider.</h4>
    <p>Emotional distress should be part of the conversation that persons with a chronic disease have with their healthcare provider on a regular basis. If it is not, then you should bring it up yourself! However, many people feel awkward bringing up issues about distress and feelings of discouragement when meeting with providers because of the short time they spend in the office and because of the large amount of material that has to be covered during any one office visit. Also, sometimes it is hard and awkward to bring up how you have been feeling emotionally - it may not be something that you have done before, especially not with your doctor. Furthermore, doctors often make suggestions for care that overload people by asking them to do too many things too quickly, by not explaining things clearly, or by not discussing things in ways that make the management plan practical and realistic. You can leave a doctor’s office far more distressed and confused than when you arrived. Most doctors, however, know that even the best disease management plan will not work if the person is distressed, frightened, depressed, or burned out. If you tell your doctor about the distress you are feeling in taking care of your chronic disease, most doctors will be glad to help you in dealing with these issues. Sometimes re-working the management plan or coming up with alternative coping behaviors can address the problem, sometimes a short course of medication can be helpful, or sometimes a referral to a behavioral specialist is in order. In most cases, a simple discussion of the problem relieves much of the tension and distress and helps to place things back into perspective. But you may have to take the initiative and tell your health care provider about how you have been feeling about your chronic disease. There are usually many health care professionals on your health care team - doctors, nurses, educators, assistants, etc. Select a person that you feel comfortable with and who you feel might listen and help. Then raise these problems directly with them.</p>

    <h4>Tip #3: Talk to family members, friends, or others with diabetes.</h4>
    <p>Put simply: express yourself and put the feelings into words. Talking about how it feels to have to constantly manage and think about your chronic disease is not necessarily whining or complaining; it is sharing your feelings in ways that inform others and in ways that force you to organize your thinking about your concerns. Simply putting feeling of emotional distress into words can help gain perspective, clarify what you feel, identify specific things that have become problematic, and assist in plans to address each aspect of the problem in a focused way. Keeping feelings inside and unexpressed often keeps you from thinking about them clearly, and they get worse over time instead of better. Seek out others who are understanding about your chronic disease and are willing to listen without necessarily telling you what to do - you don’t need fixing, you need understanding! Telling the tale is often more helpful than finding the ‘supposed’ solution, because in most cases, there simply is no solution - your chronic disease most likely will not disappear. Letting others know how you feel helps others understand what this is like for you and helps you begin to feel that you are understood and supported - options for action then tend to follow more easily because of a feeling that you are not in this alone.</p>

    <h4>Tip #4: Do one thing at a time.</h4>
    <p>When distressed, many persons with a chronic disease attempt to alter their entire management plan in the hopes of tackling all of their lifestyle problems head-on. For example, they may try to double their physical activity, sharply reduce calories with a new diet, or perhaps purchase a new blood pressure meter as a cue to test more frequently. The greater the number of things that you change at one time, the greater the probability that none of them will be accomplished or sustained over time. The lack of progress then dramatically increases feelings of frustration and failure, and things just get worse instead of better. To deal with emotional distress effectively, create a list of priorities for change and address each separately, one at a time. Talk with your doctor if you need help in coming up with a plan and choosing what to work on first. Change is difficult - give yourself a break and adopt realistic and feasible goals, goals that you actually can achieve and tackle them one at a time!</p>

    <h4>Tip #5: Pace yourself.</h4>
    <p>This tip follows directly from #4 above. The slower the pace of change, the greater the probability that the goal will be achieved and sustained. For example, people who drastically increase their physical activity may do very well for a week or two, even with sore muscles. But the probability is low that they will be able to sustain the program over time. Fatigue will increase, other lifestyle factors will compete for time and motivation to continue will suffer. The hallmark of good chronic disease management is sustained behavior, not just reaching a goal in the short-term, only to see it slip away over time. The slow pace of change enables the new behaviors to become more easily incorporated into one’s general lifestyle and the new behaviors become self-reinforcing because many small goals are achieved over time. Furthermore, the slow pace provides the freedom for each individual to experiment with alternative ways of doing things, and barriers to success are less overwhelming and can be dealt with more slowly and effectively over time. So go slowly and carefully so that you can maintain your gains over time.</p>

    <h4>Tip #6: Behavior change works best when not done alone.</h4>
    <p>Emotional distress often occurs when lifestyle, blood pressure, or other disease-related goals are not achieved. In fact, of all the tasks associated with disease management, persons with a chronic condition report that they experience the most distress about diet and exercise. A number of studies, however, have shown that for most people behavior change works best when others are involved. People tend to help each other in reaching goals, and things that you do with other people are usually sustained far longer than actions taken by you alone. Studies show that weight reduction programs work best for marital partners when both spouses choose to lose weight together. Studies of smoking cessation have shown similar results. Other examples include asking family members to help you with reminders to take medication or to monitor blood glucose or blood pressure, walking with friends or family members at a set time each day, and joining a physical activity program at a nearby neighborhood center, school or gym. By engaging with others, the probability is increased that your goals will be achieved and sustained, and your emotional distress will be reduced.</p>

    <h4>Tip #7: Focus on behavioral goals.</h4>
    <p>No person with a chronic disease can directly control their weight, blood pressure, cholesterol level, or blood glucose. People can eat less, take their medications regularly, and increase their physical activity — but these are behaviors and they are indirect methods of weight, blood pressure, or glucose control. Many persons with a chronic condition become very frustrated with how difficult it is to change lifestyle behaviors, and the frustration is increased when they follow difficult diets over time with few pounds lost. The reason is that many factors play a role in weight loss, as many factors play a role in reducing blood pressure and blood glucose levels. Body size, age, gender, ethnicity, and medications all influence these things. Setting a goal of losing 25 pounds is far more difficult and frustrating to achieve than setting a goal of staying on a 2000 calorie a day diet: a person cannot directly control weight, but a person can control the number of calories taken in. This is an important distinction that can help reduce emotional distress and general frustration: focus on goals that you can directly control with behavior. Persons with diabetes can control the number of calories consumed, the amount of physical energy expended, the regularity of taking medications, and the frequency of glucose monitoring. And completing all of these tasks regularly as part of an overall management plan will have an effect on diabetes outcomes if the plan is put together properly. A focus on behavioral goals, rather than goals that are less directly controllable, keeps persons with a chronic disease focused on things that they can actually do and goals that they can achieve and sustain. Thus, frustration and disappointment can be reduced because the focus is on your behavior, not only on the results of a blood test or other indirect indicator. If behavioral goals have been achieved but A1C, cholesterol, or blood pressure levels remain high, then it is time to review the management plan with your healthcare provider.</p>

    <h4>Tip #8: Take responsibility for your chronic disease.</h4>
    <p>Even though healthcare providers play crucial roles in chronic disease care, managing your disease on a day to day basis is up to you. This fact can be either overwhelming or empowering, acknowledging full well that it is a tough job in either case. It can be empowering by motivating you to be gather new information, work to solve problems in your disease management, devise experiments to test how different behaviors affect your clinical measures, and raise important issues of concern directly your healthcare provider. This may involve using a health library, the web, a resource center, and others in your community so that information about alternatives and strategies for care can be gathered. It also may involve raising concerns with providers and seeking out educators, nurses, physicians, and others. Studies clearly show that persons with a chronic disease who are engaged in care, who take responsibility for their disease and who are often one step ahead of their healthcare providers do far better over time than persons who remain passive and uninvolved in their care. They are less frustrated, more inquisitive, and more upbeat about managing their disease than those who simply ‘go along’ with what they are told. Holding back, staying in the background, and feeling afraid to ask or pursue questions and problems increases the probability of struggling alone, and feeling overwhelmed and over-burdened, since far fewer tools needed for success have been obtained.</p>

    <h4>Conclusion</h4>
    <p>Caring well for your chronic disease requires persistence, motivation, knowledge, and collaboration with family members, friends, and a team of healthcare professionals. Over time life changes, chronic disease changes, medications change, and management requirements change as well. The seemingly endless series of personal burdens associated with a chronic disease often leads to frustration, fatigue and emotional distress, which can have negative effects on disease management, outcomes and general well-being. High levels of disease-related emotional distress are, understandably, very common among persons with a chronic condition. It is important to pay attention to them, to use them as signs and signals for taking action, and to address them with healthcare providers. Emotional distress is as important in chronic disease care as any medication taken or any behavior routinely practiced. Being aware of and taking action about your disease-related emotional distress is an inherent part of good personal chronic disease care.</p>

























{/block}
